Removing reference to mountain_lion to fix error on MacOSX
* Updating to behave like qt.rb where it does not depend on mountain_lion as seen here: https://github.com/Homebrew/homebrew-core/blob/master/Formula/qt.rb
* Fixes this error that occurs when doing a brew install with this formula:
Error: clearcorrect/ccdev/qt: unknown version :mountain_lion